### PR TITLE
New version 0.4.1 (mostly bug fix release)

### PR DESCRIPTION
**Pull request by Gury8**
New version 0.4.1

- Bug fixes:
  - removed duplication code in variable declaration block of Mad Pascal listing
  - proper handling of machine language following the PROC/FUNC declaration statement
  - PROC/FUNC parameters (automatic translation of character to ATASCII value in Mad Pascal listing code, f.e.: SetBlock(flags, 8190, 'T) <==> FillChar(FLAGS, 8190, 84);
  - branches:
    - proper handling of IF condition with brackets (f.e. IF (X+Y)<=RADIUS THEN BINGO==+1 FI)
    - better handling of WHILE and FOR closing OD statements
  - proper handling of increments with BYTE ARRAY variables (f.e. DL(4)==+1)
  - PrintD, PrintDE proper comma (,) determination in text

-Misc:
  - BYTE ARRAY variable declaration with continuous bytes supported (f.e. BYTE ARRAY DL=[$70$70$70$56$C$20$41$1$20])
  - Added # comparison operator (substitution for <>)
  - Some Mad Pascal listing code indentation corrections
  - Added missing line ending character
  - Removed some unused code
  - Code optimization

### CODE REVIEW

**Comment by zbyti** [comment]
fpc -Mdelphi -vh -O3 effectus.pas 
Hint: Start of reading config file /etc/fpc.cfg
Hint: End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 3.0.4+dfsg-18ubuntu2 [2018/08/29] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling effectus.pas
effectus.pas(32,2) Note: APPTYPE is not supported by the target OS
Compiling decl.pas
Compiling shell.pas
Compiling lib.pas
lib.pas(39,75) Error: Identifier not found "TFlags"
lib.pas(43,76) Error: Identifier not found "TFlags"
lib.pas(49,1) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode

**Comment by Gury8** [comment]
> fpc -Mdelphi -vh -O3 effectus.pas
> Hint: Start of reading config file /etc/fpc.cfg
> Hint: End of reading config file /etc/fpc.cfg
> Free Pascal Compiler version 3.0.4+dfsg-18ubuntu2 [2018/08/29] for x86_64
> Copyright (c) 1993-2017 by Florian Klaempfl and others
> Target OS: Linux for x86-64
> Compiling effectus.pas
> effectus.pas(32,2) Note: APPTYPE is not supported by the target OS
> Compiling decl.pas
> Compiling shell.pas
> Compiling lib.pas
> lib.pas(39,75) Error: Identifier not found "TFlags"
> lib.pas(43,76) Error: Identifier not found "TFlags"
> lib.pas(49,1) Fatal: There were 2 errors compiling module, stopping
> Fatal: Compilation aborted
> Error: /usr/bin/ppcx64 returned an error exitcode

Ups, I forgot to upload lib.pas file. In progress... :)

**Comment by Gury8** [comment]
I hope it is ok now. Let's fight against bugs further :)

**Comment by zbyti** [comment]
> I hope it is ok now. Let's fight against bugs further :)

Now is OK! :+1:

**Comment by zbyti** [comment]
@Gury8 For start I found problem if source file have '-' in name.

program zp-sievePrg; produces error during compilation

**Comment by zbyti** [comment]
@Gury8 resieve.eff still can't count correctly.

**Comment by zbyti** [comment]
@Gury8 scroll.eff produces multibegin in .pas

**Comment by zbyti** [comment]
Here my code samples for testing Effectus
[Effectus-code-saples-for-tests.zip](https://github.com/mariusz-buk/effectus/files/4589644/Effectus-code-saples-for-tests.zip)
 :]

**Comment by Gury8** [comment]
Ok, I will revise the code. hscroll.eff succeded to compile, with different result, but anyway. The way Action! can operate with syntax, is extraordinary.

I have to dig into a solution for this kind of statement:
BYTE ARRAY
  DL=[$70$70$70$56$C$20$41$1$20],
  TEXT="NNNNNNNNNNNNNNNNNNNNtajemnice@atariNNNNNNNNNNNNNNNNNNNN"

fillscr works too, even faster than by running on original Action! cartridge.

DEFINEs will be look after in next release, because extra pass will have to be performed to work for any case.

**Comment by Gury8** [comment]
Thanks for testing and providing test examples. Current test suite can be tested via test.bat batch file in the package. All new working examples will be included in this batch.

**Comment by zbyti** [comment]
@Gury8 If you don't provide mads and mp binary (or sources) /base is not needed anymore.

**Comment by zbyti** [comment]
> Ok, I will revise the code. hscroll.eff succeded to compile, with different result, but anyway. The way Action! can operate with syntax, is extraordinary.
> 
> I have to dig into a solution for this kind of statement:
> BYTE ARRAY
> DL=[$70$70$70$56$C$20$41$1$20],
> TEXT="NNNNNNNNNNNNNNNNNNNNtajemnice@atariNNNNNNNNNNNNNNNNNNNN"
> 
> fillscr works too, even faster than by running on original Action! cartridge.
> 
> DEFINEs will be look after in next release, because extra pass will have to be performed to work for any case.

not hscroll but scroll.eff produce multibegin

**Comment by zbyti** [comment]
@Gury8 Anyway, great work! :+1:

**Comment by Gury8** [comment]
> @Gury8 If you don't provide mads and mp binary (or sources) /base is not needed anymore.

Yes, I know, but I included them intentionally in published package, so users can run all is needed to compile to binary. This repo has slightly different directory and file scheme for the project.

**Comment by Gury8** [comment]
I will publish this vesion anyway to keep things in order for easier further maintenance of the code. Next is to fix known problems, including your test-suit. Effectus is still fragile, but it can be used if you are gentle with it :)

**Comment by zbyti** [comment]
>Effectus is still fragile, but it can be used if you are gentle with it :)

Same as Action! you must be gentle ;)

I will contynously test my game in Action! https://github.com/zbyti/a8-action-scramble with Effectus ;)

**Comment by Gury8** [comment]
Many thanks!
Yes, I noticed your work and experimentation with Action! code, now with Scramble game. Fascinating stuff... keep up the good work.

**Pull request merged**
